### PR TITLE
Feature/salesforce migration

### PR DESCRIPTION
**Pull request by davidesner**
Added Salesforce migration from HTNS to our kds component. Added support for config row transfer and state transfer. Tested here https://connection.keboola.com/admin/projects/5415/orchestrations/724714423/tasks. Also the orchestration task replacement is removed as it's too invasive.

It breaks the old configuration because the `migration_status` is added to the root of `Configuration` object. It ends with error `
Unrecognized option "migrationStatus" under "container"` The check on the component execution should be removed or perhaps this parameter should be added to the `parameters` section instead.

### CODE REVIEW

**Comment by webrouse** [comment]
@davidesner I'll look at it in the afternoon or evening -> now we have the end of the sprint and the planning of the next.

**Review by webrouse — APPROVED** [review]
LGTM

The problem with `migrationStatus` is still discussed. We will probably move it to `runtime.migrationStatus` so that the docker runner does not have a problem with that.

**Comment by webrouse** [comment]
@davidesner do you merge this PR or is there something else on my part?

The UI will also check `runtime.migrationStatus`, they have a Jira task for it.
https://keboola.atlassian.net/browse/UI-2152

**Comment by davidesner** [comment]
@webrouse we have discussed today, that we will update the script & component a bit so it is possible define (secretly) the destination bucket so that the migration will not change it and keep the original. The component produces the same tables & the script transfers the state so it should be fine. Otherwise the script would not be much useful.

What do you think?

**Comment by webrouse** [comment]
@davidesner 

1. About `runtime.migrationStatus` - I found out from the UI team that it is not necessary to modify the UI, but just modify this component. As the UI reads the status via a sync action. Can yo prepare PR for this change? I don't have time now.... just change the key in the code from `migrationStatus` to `runtime.migrationStatus` -> it will go through the docker runner validation and it will be possible to run the old configuration as well
2. `destination bucket so that the migration will not change it and keep the original` can you please explain it in more detail? or send PR? with an example? so the old configuration will use old bucket and new configration modified? I dont understand the question.

**Comment by davidesner** [comment]
> @davidesner
> 
> 1. About `runtime.migrationStatus` - I found out from the UI team that it is not necessary to modify the UI, but just modify this component. As the UI reads the status via a sync action. Can yo prepare PR for this change? I don't have time now.... just change the key in the code from `migrationStatus` to `runtime.migrationStatus` -> it will go through the docker runner validation and it will be possible to run the old configuration as well
> 2. `destination bucket so that the migration will not change it and keep the original` can you please explain it in more detail? or send PR? with an example? so the old configuration will use old bucket and new configration modified? I dont understand the question.

@webrouse I have updated the component to use the `runtime.migrationStatus`

Regarding the point `2.` The component now does not use the default bucket but has a hidden option to override the output bucket name. This is to make the migration easier for the users -> the output tables/buckets are staying the same, they will just need to update the orchestrations manually. The migration will override the output bucket to use the original one. 

Also the state is transferred so it will not force full load after migration and will just continue from where it left off.

If you're ok with it, the PR is ready to be merged. I also tested it in a project manually.

**Comment by davidesner** [comment]
May we also update the migration message that is going to be displayed to users to reflect these changes?

**Review by webrouse — APPROVED** [review]
LGTM

**Comment by webrouse** [comment]
(I will remove the conflicts and merge it)

**Comment by webrouse** [comment]
Rebased, removed conflicts -> https://github.com/keboola/config-migration-tool/pull/88

**Comment by webrouse** [comment]
@davidesner PR has been merged (https://github.com/keboola/config-migration-tool/pull/88), and version `1.16.0` has been released.

**Comment by webrouse** [comment]
@davidesner 

> May we also update the migration message that is going to be displayed to users to reflect these changes?

Please test it on the production, that everything is ok. If you want some changes in the UI, it would be best to ask the UI team directly.

**Pull request closed without merging**
